Version: 1
ListenAddress: tcp(ip4(127.0.0.1),42001)
Bandwidth:
  MaxSendBytesPerSeconds: 33554432
  MaxReceiveBytesPerSeconds: 33554432
SessionConnector:
  TcpConnector:
    Proxy:
      Type: None
SessionAccepter:
  TcpAccepter:
    UseUpnp: true
    ListenAddress: tcp(ip4(127.0.0.1),32001)
