Version: 1
ListenAddress: tcp(ip4(127.0.0.1),40001)
Engines:
  Connectors:
    TcpConnector:
      Bandwidth:
        MaxSendBytesPerSeconds: 33554432
        MaxReceiveBytesPerSeconds: 33554432
      Connecting:
        Enabled: true
        Proxy: 
      Accepting:
        Enabled: true
        ListenAddresses:
        - tcp(ip4(127.0.0.1),40000)
        UseUpnp: true
  Exchangers:
    ContentExchanger:
      MaxConnectionCount: 32
    DeclaredMessageExchanger:
      MaxConnectionCount: 32
