Version: 1
Verbose: true
StorageDirectoryPath: storage
LogsDirectoryPath: logs
ListenAddress: tcp(ip4(127.0.0.1),41001)
Bandwidth:
  MaxSendBytesPerSeconds: 33554432
  MaxReceiveBytesPerSeconds: 33554432
SessionConnector:
  TcpConnector:
    Proxy:
      Type: None
SessionAccepter:
  TcpAccepter:
    UseUpnp: true
    ListenAddress: tcp(ip4(127.0.0.1),31001)
