- Includes:
    - ./refs/core/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Xeus.Models/Omnius.Xeus.Models.rpf
      Output: ./src/Omnius.Xeus.Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines/Omnius.Xeus.Engines.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines/Implementations/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Remoting/Omnius.Xeus.Remoting.rpf
      Output: ./src/Omnius.Xeus.Remoting/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Services/Omnius.Xeus.Services.Models.rpf
      Output: ./src/Omnius.Xeus.Services/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Services/Omnius.Xeus.Services.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Services/Internal/Models/_RocketPack/_Generated.cs
