- Includes:
    - ./refs/core/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Xeus.Engines/Omnius.Xeus.Engines.Models.rpf
      Output: ./src/Omnius.Xeus.Engines/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Connectors.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Connectors/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Storages.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Storages/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Mediators.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Mediators/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Exchangers.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Exchangers/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Daemon/Omnius.Xeus.Daemon.rpf
      Output: ./src/Omnius.Xeus.Daemon/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Services/Omnius.Xeus.Services.Models.rpf
      Output: ./src/Omnius.Xeus.Services/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Services.Implementations/Omnius.Xeus.Services.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Services.Implementations/Internal/Models/_RocketPack/_Generated.cs
