- Includes:
    - ./refs/core/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Xeus.Engines/Omnius.Xeus.Engines.Models.rpf
      Output: ./src/Omnius.Xeus.Engines/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Connectors.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Connectors/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Storages.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Storages/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Mediators.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Mediators/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Engines.Implementations/Omnius.Xeus.Engines.Exchangers.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Engines.Implementations/Exchangers/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Api/Omnius.Xeus.Api.rpf
      Output: ./src/Omnius.Xeus.Api/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Service/Omnius.Xeus.Service.Models.rpf
      Output: ./src/Omnius.Xeus.Service/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Xeus.Service.Implementations/Omnius.Xeus.Service.Internal.Models.rpf
      Output: ./src/Omnius.Xeus.Service.Implementations/Internal/Models/_RocketPack/_Generated.cs
