name: Submodules Sync

on:
  workflow_dispatch:

jobs:
  sync:
    name: Submodules Sync
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Git Sumbodule Update
      run: git submodule update --init --remote --recursive

    - name: Create Pull-Request
      uses: peter-evans/create-pull-request@v2
      with:
        title: Update Sumbodules
        branch: update/submodules
        token: ${{ secrets.GITHUB_TOKEN }}
